import assert from "node:assert/strict";
import test from "node:test";
import { createOperationalHardening } from "../packages/domain/src/operational-hardening.mjs";
import { createFinalReadiness } from "../packages/domain/src/final-readiness.mjs";
const owner={role:"project-owner",subject:"owner-one"}, admin={role:"admin",subject:"admin-one"}, viewer={role:"viewer",subject:"viewer-one"}; const projectId="project-one"; const clock=()=>"2026-09-10T00:00:00.000Z";

test("hardening preserves non-weakenable retention, dry-runs cleanup and reports bounded coverage",()=>{
 const hardening=createOperationalHardening({now:clock}); assert.throws(()=>hardening.setRetention({actor:admin,projectId,retention:{auditDays:2}}),/cannot be below/); hardening.setRetention({actor:admin,projectId,retention:{auditDays:400,evidenceDays:400,securityDays:800}}); const cleanup=hardening.planCleanup({actor:admin,projectId,jobId:"cleanup-one",candidates:[{id:"record-one",kind:"audit",digest:`sha256:${"a".repeat(64)}`,recordedAt:"2020-01-01T00:00:00.000Z"}]}); assert.equal(cleanup.dryRun,true); assert.equal(cleanup.eligible.length,1); assert.throws(()=>hardening.page({actor:viewer,projectId,records:[],limit:101}),/Query/); hardening.recordAudit({actor:admin,projectId,auditId:"audit-one",kind:"accessibility",tool:"tools/audit/accessibility",toolVersion:"1",evidenceDigest:`sha256:${"b".repeat(64)}`,checks:{total:3,passed:3}}); assert.ok(hardening.report({actor:viewer,projectId}).coverage.missing.includes("security"));
});

test("final readiness keeps migration compatible, requires isolated scenarios and requires explicit owner acceptance before a pilot proposal",()=>{
 const readiness=createFinalReadiness({now:clock}); readiness.planMigration({actor:admin,projectId,migrationId:"migration-one",oldRoute:"/old",newRoute:"/new",compatibilityUntil:"2026-10-01T00:00:00.000Z"}); assert.equal(readiness.rebuildReadModel({actor:admin,projectId,modelId:"model-one",beforeState:{a:1},afterState:{a:1}}).equal,true);
 for(const kind of ["e2e-multi-project","adversarial-access","crash-resume","test-transfer"]) readiness.recordScenario({actor:admin,projectId,scenarioId:`scenario-${kind}`,kind,tool:"tests/scenario",toolVersion:"1",evidenceDigest:`sha256:${"c".repeat(64)}`,checks:{total:2,passed:2},projects:kind==="e2e-multi-project"?[projectId,"project-two"]:[],details:{safe:true}}); const review=readiness.readinessReview({actor:admin,projectId,reviewId:"review-one",rollbackRef:"hero://rollback"}); assert.equal(review.state,"ready-for-owner-acceptance"); assert.throws(()=>readiness.pilotProposal({actor:owner,projectId,proposalId:"pilot-one",reviewId:"review-one",scope:"pilot"}),/acceptance/); readiness.accept({actor:owner,projectId,reviewId:"review-one",artifactIdentity:"artifact-identity-001"}); assert.equal(readiness.pilotProposal({actor:owner,projectId,proposalId:"pilot-one",reviewId:"review-one",scope:"narrow Test-only proposal"}).execution,"forbidden-without-separate-pilot-authorization");
});
