import { randomUUID } from "node:crypto";
import { COMMAND_RISKS, COMMAND_STATES } from "../../contracts/src/backoffice-command-center.mjs";
import { createWorkflowEngine } from "./workflow-engine.mjs";

const ID = /^[A-Za-z][A-Za-z0-9._:-]{2,127}$/;
const HIGH = new Set(["high", "critical"]);
function copy(value) { return Object.freeze(structuredClone(value)); }
function id(label, value) { if (typeof value !== "string" || !ID.test(value)) throw new CommandCenterError("INVALID_IDENTIFIER", `${label} is invalid.`, 400); return value; }
function editor(actor) { if (!actor || !["project-owner", "admin"].includes(actor.role)) throw new CommandCenterError("PROJECT_WRITE_REQUIRED", "Project owner or admin access is required.", 403); return actor; }
function owner(actor) { if (actor?.role !== "project-owner") throw new CommandCenterError("OWNER_REQUIRED", "Owner access is required.", 403); return actor; }
export class CommandCenterError extends Error { constructor(code, message, statusCode = 409) { super(message); this.name = "CommandCenterError"; this.code = code; this.statusCode = statusCode; } }

export function createCommandCenter({ now = () => new Date().toISOString(), globalStop = () => false, workflow = createWorkflowEngine({ now }), heavyRunLimit = 2 } = {}) {
  const intents = new Map(); const approvals = new Map(); const templates = new Map(); const preauthorizations = new Map(); const queue = []; const locks = new Map(); const executed = new Map();
  if (!Number.isInteger(heavyRunLimit) || heavyRunLimit < 1 || heavyRunLimit > 20) throw new Error("heavyRunLimit is invalid.");
  function makeDecision(intent, authorizationSnapshotId) { return copy({ decisionId: `decision-${randomUUID()}`, commandId: intent.commandId, projectId: intent.projectId, authorizationSnapshotId: id("authorizationSnapshotId", authorizationSnapshotId), version: 1, state: HIGH.has(intent.risk) ? "approval-required" : intent.executionMode === "direct-if-policy" ? "eligible-for-direct" : "approval-required", recordedAt: now() }); }
  function get(commandId) { const item = intents.get(id("commandId", commandId)); if (!item) throw new CommandCenterError("COMMAND_NOT_FOUND", "Command was not found.", 404); return item; }
  function activeHeavy() { return queue.filter(item => item.state === "running" && item.heavy).length; }
  function compatible(lock, entry) { return !lock || lock.commandId === entry.commandId; }
  return Object.freeze({
    createIntent({ actor, projectId, commandId, action, risk = "medium", payload = {}, correlationId, idempotencyKey, executionMode = "approval" }) { editor(actor); id("projectId", projectId); id("commandId", commandId); id("correlationId", correlationId); id("idempotencyKey", idempotencyKey); if (!COMMAND_RISKS.includes(risk) || typeof action !== "string" || action.length < 3) throw new CommandCenterError("COMMAND_INVALID", "Action or risk is invalid.", 400); if (intents.has(commandId)) { const prior = intents.get(commandId); if (prior.idempotencyKey === idempotencyKey) return prior; throw new CommandCenterError("COMMAND_IDEMPOTENCY_CONFLICT", "Command id already exists with different idempotency.", 409); } const intent = copy({ commandId, projectId, action: action.slice(0, 160), risk, payload: structuredClone(payload), correlationId, idempotencyKey, executionMode, state: "draft", createdAt: now(), createdBy: actor.subject }); intents.set(commandId, intent); return intent; },
    authorize({ actor, commandId, authorizationSnapshotId }) { editor(actor); const intent = get(commandId); const decision = makeDecision(intent, authorizationSnapshotId); const next = copy({ ...intent, decision, state: decision.state === "eligible-for-direct" ? "approved" : "awaiting-approval" }); intents.set(commandId, next); return next; },
    createApprovalTemplate({ actor, projectId, templateId, name, allowedRisks = ["low", "medium"], expiresInMinutes = 60 }) { editor(actor); id("projectId", projectId); id("templateId", templateId); if (!Array.isArray(allowedRisks) || allowedRisks.some(item => !COMMAND_RISKS.includes(item)) || !Number.isInteger(expiresInMinutes) || expiresInMinutes < 1 || expiresInMinutes > 43_200) throw new CommandCenterError("APPROVAL_TEMPLATE_INVALID", "Approval template is invalid.", 400); const template = copy({ templateId, projectId, name: String(name).slice(0, 160), allowedRisks: [...new Set(allowedRisks)], expiresInMinutes, version: (templates.get(templateId)?.version ?? 0) + 1, createdAt: now(), createdBy: actor.subject }); templates.set(templateId, template); return template; },
    approve({ actor, commandId, templateId = null, reason = "approved" }) { editor(actor); const intent = get(commandId); if (intent.state !== "awaiting-approval") throw new CommandCenterError("APPROVAL_STATE_INVALID", "Command is not awaiting approval.", 409); const template = templateId ? templates.get(id("templateId", templateId)) : null; if (template && (template.projectId !== intent.projectId || !template.allowedRisks.includes(intent.risk))) throw new CommandCenterError("APPROVAL_TEMPLATE_SCOPE_INVALID", "Template does not permit this command.", 409); const approval = copy({ approvalId: `approval-${randomUUID()}`, commandId, projectId: intent.projectId, state: "approved", templateId, reason: String(reason).slice(0, 500), approvedAt: now(), approvedBy: actor.subject, expiresAt: new Date(Date.parse(now()) + (template?.expiresInMinutes ?? 60) * 60_000).toISOString() }); approvals.set(commandId, approval); const next = copy({ ...intent, state: "approved", approval }); intents.set(commandId, next); return next; },
    preauthorizeProduction({ actor, projectId, preauthorizationId, changeType, validFrom, validUntil, artifactDigest, testEvidenceRef }) { owner(actor); id("projectId", projectId); id("preauthorizationId", preauthorizationId); if (!/^sha256:[a-f0-9]{64}$/.test(artifactDigest) || !String(testEvidenceRef).startsWith("hero://") || Number.isNaN(Date.parse(validFrom)) || Number.isNaN(Date.parse(validUntil)) || Date.parse(validUntil) <= Date.parse(validFrom)) throw new CommandCenterError("PRODUCTION_PREAUTH_INVALID", "Production preauthorization limits are invalid.", 400); const record = copy({ preauthorizationId, projectId, changeType: String(changeType).slice(0, 120), validFrom, validUntil, artifactDigest, testEvidenceRef, state: "recorded-not-a-deploy-grant", createdAt: now(), createdBy: actor.subject }); preauthorizations.set(preauthorizationId, record); return record; },
    queue({ actor, commandId, heavy = false, resourceClaim = null, priority = 0 }) { editor(actor); const intent = get(commandId); if (globalStop()) throw new CommandCenterError("GLOBAL_STOP_ACTIVE", "Global Stop blocks new dispatch.", 409); if (intent.state !== "approved") throw new CommandCenterError("COMMAND_NOT_APPROVED", "Command must be approved before queueing.", 409); if (intent.approval && Date.parse(intent.approval.expiresAt) <= Date.parse(now())) throw new CommandCenterError("APPROVAL_EXPIRED", "Approval expired before dispatch.", 409); if (!Number.isInteger(priority) || priority < -100 || priority > 100) throw new CommandCenterError("PRIORITY_INVALID", "Priority is invalid.", 400); const entry = copy({ commandId, projectId: intent.projectId, correlationId: intent.correlationId, state: "queued", heavy: Boolean(heavy), resourceClaim, priority, queuedAt: now(), queuedBy: actor.subject, attempts: 0, checkpoint: null }); queue.push(entry); intents.set(commandId, copy({ ...intent, state: "queued" })); return entry; },
    dispatchNext({ actor }) { editor(actor); if (globalStop()) throw new CommandCenterError("GLOBAL_STOP_ACTIVE", "Global Stop blocks dispatch.", 409); const candidates = queue.filter(item => item.state === "queued").sort((a, b) => (b.priority + Math.floor((Date.parse(now()) - Date.parse(b.queuedAt)) / 60000)) - (a.priority + Math.floor((Date.parse(now()) - Date.parse(a.queuedAt)) / 60000)) || a.commandId.localeCompare(b.commandId)); const next = candidates.find(item => (!item.heavy || activeHeavy() < heavyRunLimit) && compatible(locks.get(item.resourceClaim), item)); if (!next) return null; if (next.resourceClaim) locks.set(next.resourceClaim, next); const running = copy({ ...next, state: "running", startedAt: now(), attempts: next.attempts + 1 }); queue.splice(queue.indexOf(next), 1, running); const intent = get(running.commandId); const run = workflow.create({ runId: `run-${running.commandId}`, taskId: running.commandId, actor: { kind: "project-owner", id: actor.subject }, idempotencyKey: `workflow-${running.commandId}`, correlationId: running.correlationId }); workflow.apply({ runId: run.workflow.runId, action: "plan", actor: { kind: "project-owner", id: actor.subject }, idempotencyKey: `plan-${running.commandId}` }); workflow.apply({ runId: run.workflow.runId, action: "queue", actor: { kind: "project-owner", id: actor.subject }, idempotencyKey: `queue-${running.commandId}` }); workflow.apply({ runId: run.workflow.runId, action: "start", actor: { kind: "project-owner", id: actor.subject }, idempotencyKey: `start-${running.commandId}` }); intents.set(running.commandId, copy({ ...intent, state: "running", runId: run.workflow.runId })); return copy({ entry: running, runId: run.workflow.runId }); },
    checkpoint({ actor, commandId, checkpoint, reason = "checkpoint" }) { editor(actor); const index = queue.findIndex(item => item.commandId === commandId && item.state === "running"); if (index < 0) throw new CommandCenterError("RUN_NOT_ACTIVE", "No active run exists for command.", 404); const next = copy({ ...queue[index], checkpoint: { value: structuredClone(checkpoint), reason: String(reason).slice(0, 300), at: now() }, state: "paused" }); queue.splice(index, 1, next); return next; },
    resume({ actor, commandId }) { editor(actor); const index = queue.findIndex(item => item.commandId === commandId && item.state === "paused"); if (index < 0) throw new CommandCenterError("RUN_NOT_PAUSED", "No paused run exists for command.", 404); const next = copy({ ...queue[index], state: "queued", resumedAt: now() }); queue.splice(index, 1, next); return next; },
    complete({ actor, commandId, outcome = "completed" }) { editor(actor); const index = queue.findIndex(item => item.commandId === commandId && ["running", "paused"].includes(item.state)); if (index < 0) throw new CommandCenterError("RUN_NOT_ACTIVE", "No active run exists for command.", 404); const completed = copy({ ...queue[index], state: outcome === "completed" ? "completed" : "failed", completedAt: now() }); queue.splice(index, 1, completed); if (completed.resourceClaim) locks.delete(completed.resourceClaim); const intent = get(commandId); intents.set(commandId, copy({ ...intent, state: completed.state })); executed.set(commandId, completed); return completed; },
    operations({ actor, projectId }) { reader(actor); return copy({ queue: queue.filter(item => item.projectId === projectId), completed: [...executed.values()].filter(item => item.projectId === projectId), approvals: [...approvals.values()].filter(item => item.projectId === projectId), locks: [...locks.entries()].filter(([, item]) => item.projectId === projectId).map(([resourceClaim, item]) => ({ resourceClaim, commandId: item.commandId })), heavyRunLimit }); }
  });
}
function reader(actor) { if (!actor || !["project-owner", "admin", "viewer"].includes(actor.role)) throw new CommandCenterError("PROJECT_READ_REQUIRED", "Project access is required.", 403); return actor; }
