import { createHash } from "node:crypto";
import { DELIVERY_TARGETS, DELIVERY_RELEASE_STATES } from "../../contracts/src/delivery-control.mjs";
const ID=/^[A-Za-z][A-Za-z0-9._:-]{2,127}$/;const SENSITIVE=/(payload|email|phone|address|secret|password|token|credential|authorization|private.?key)/i;const copy=x=>Object.freeze(structuredClone(x));const id=(n,v)=>{if(typeof v!=="string"||!ID.test(v))throw new DeliveryError("INVALID_IDENTIFIER",`${n} is invalid.`,400);return v;};const write=a=>{if(!a||!["project-owner","admin"].includes(a.role))throw new DeliveryError("PROJECT_WRITE_REQUIRED","Project owner or admin access is required.",403);};const read=a=>{if(!a||!["project-owner","admin","viewer"].includes(a.role))throw new DeliveryError("PROJECT_READ_REQUIRED","Project access is required.",403);};const redact=o=>!o||typeof o!=="object"?o:Object.fromEntries(Object.entries(o).map(([k,v])=>[k,SENSITIVE.test(k)?"[redacted]":redact(v)]));
export class DeliveryError extends Error { constructor(code,message,statusCode=409){super(message);this.name="DeliveryError";this.code=code;this.statusCode=statusCode;} }
export function createDeliveryControl({now=()=>new Date().toISOString()}={}){const telemetry=new Map(),breakGlass=new Map(),releases=new Map(),artifacts=new Map(),bundles=new Map(),rehearsals=new Map(),acceptance=new Map();const get=(map,key,projectId,code)=>{const x=map.get(key);if(!x||x.projectId!==projectId)throw new DeliveryError(code,"Record was not found in this project.",404);return x;};
 return Object.freeze({
  ingestTelemetry({actor,projectId,telemetryId,kind,metadata={}}){write(actor);id("projectId",projectId);id("telemetryId",telemetryId);if(!["health","metric","sanitized-log","trace-metadata"].includes(kind)||Object.keys(metadata).some(k=>SENSITIVE.test(k)))throw new DeliveryError("TELEMETRY_REJECTED","Only allowlisted and sanitized Production telemetry is accepted.",400);const item=copy({projectId,telemetryId,kind,metadata:redact(metadata),payload:"forbidden",recordedAt:now(),recordedBy:actor.subject});telemetry.set(telemetryId,item);return item;},
  requestBreakGlass({actor,projectId,requestId,scope,reason,expiresAt}){if(!actor||actor.role!=="project-owner")throw new DeliveryError("OWNER_REQUIRED","Only owner may request break-glass.",403);id("requestId",requestId);if(typeof scope!=="string"||scope.length<3||typeof reason!=="string"||reason.length<8||Date.parse(expiresAt)<=Date.parse(now()))throw new DeliveryError("BREAK_GLASS_INVALID","Scope, reason and future expiry are required.",400);const item=copy({projectId,requestId,scope:scope.slice(0,160),reason:reason.slice(0,500),expiresAt,state:"approval-required",dataAccess:"not-granted",audit:true,createdAt:now()});breakGlass.set(requestId,item);return item;},
  createRelease({actor,projectId,releaseId,testedCommit}){write(actor);id("releaseId",releaseId);if(!/^[a-f0-9]{7,64}$/i.test(testedCommit))throw new DeliveryError("COMMIT_INVALID","A tested Git commit is required.",400);const item=copy({projectId,releaseId,testedCommit:testedCommit.toLowerCase(),state:"tested",history:[{state:"tested",at:now(),by:actor.subject}],deploy:"not-executed"});releases.set(releaseId,item);return item;},
  transitionRelease({actor,projectId,releaseId,state,reason=""}){write(actor);const prior=get(releases, id("releaseId",releaseId),projectId,"RELEASE_NOT_FOUND");if(!DELIVERY_RELEASE_STATES.includes(state)||!({tested:["approved","blocked"],approved:["ready","blocked"],ready:["deployed","blocked"],deployed:["rolled-back"],blocked:[],"rolled-back":[]}[prior.state]??[]).includes(state))throw new DeliveryError("RELEASE_TRANSITION_INVALID","Release transition is not allowed.",409);const next=copy({...prior,state,history:[...prior.history,{state,at:now(),by:actor.subject,reason:String(reason).slice(0,500)}],deploy:state==="deployed"?"record-only-separate-dispatch-required":prior.deploy});releases.set(releaseId,next);return next;},
  registerArtifact({actor,projectId,artifactId,digest,provenance,attestationRef,sbomRef}){write(actor);id("artifactId",artifactId);if(!/^sha256:[a-f0-9]{64}$/i.test(digest)||![provenance,attestationRef,sbomRef].every(v=>typeof v==="string"&&v.startsWith("hero://")))throw new DeliveryError("ARTIFACT_INVALID","Digest and internal provenance, attestation and SBOM references are required.",400);const item=copy({projectId,artifactId,digest:digest.toLowerCase(),provenance,attestationRef,sbomRef,registeredAt:now(),registeredBy:actor.subject});artifacts.set(artifactId,item);return item;},
  deliveryMatrix({actor,projectId,targets}){write(actor);const entries=Object.entries(targets??{});if(!entries.length||entries.some(([target,artifactId])=>!DELIVERY_TARGETS.includes(target)||!get(artifacts,String(artifactId),projectId,"ARTIFACT_NOT_FOUND")))throw new DeliveryError("DELIVERY_MATRIX_INVALID","Every target requires a registered project artifact.",400);return copy({projectId,targets:Object.fromEntries(entries),createdAt:now(),createdBy:actor.subject});},
  createBundle({actor,projectId,bundleId,artifactIds,sourceRef,configRef,migrationRef,deployRef,docsRef,reportsRef}){write(actor);id("bundleId",bundleId);const refs=[sourceRef,configRef,migrationRef,deployRef,docsRef,reportsRef];if(!Array.isArray(artifactIds)||!artifactIds.length||artifactIds.some(x=>!get(artifacts,String(x),projectId,"ARTIFACT_NOT_FOUND"))||refs.some(v=>typeof v!=="string"||!v.startsWith("hero://")))throw new DeliveryError("BUNDLE_INVALID","Bundle must contain registered artifacts and internal, secret-free references.",400);const manifest={projectId,bundleId,artifactIds:[...artifactIds].sort(),sourceRef,configRef,migrationRef,deployRef,docsRef,reportsRef};const item=copy({...manifest,digest:`sha256:${createHash("sha256").update(JSON.stringify(manifest)).digest("hex")}`,state:"manifest-only-no-export",createdAt:now(),createdBy:actor.subject});bundles.set(bundleId,item);return item;},
  verifyPortability({actor,projectId,bundleId,targetId,result}){write(actor);const bundle=get(bundles,id("bundleId",bundleId),projectId,"BUNDLE_NOT_FOUND");id("targetId",targetId);if(!["passed","failed"].includes(result))throw new DeliveryError("PORTABILITY_INVALID","Portability result is invalid.",400);const item=copy({projectId,bundleId:bundle.bundleId,targetId,result,mode:"deterministic-test-evidence-no-external-target",recordedAt:now(),recordedBy:actor.subject});rehearsals.set(`${bundleId}:${targetId}:portability`,item);return item;},
  rehearseRecovery({actor,projectId,bundleId,kind,result,evidenceRef}){write(actor);get(bundles,id("bundleId",bundleId),projectId,"BUNDLE_NOT_FOUND");if(!["backup","restore","upgrade","rollback"].includes(kind)||!["passed","failed"].includes(result)||typeof evidenceRef!=="string"||!evidenceRef.startsWith("hero://"))throw new DeliveryError("REHEARSAL_INVALID","Recovery rehearsal is invalid.",400);const item=copy({projectId,bundleId,kind,result,evidenceRef,mode:"rehearsal-evidence-only",recordedAt:now(),recordedBy:actor.subject});rehearsals.set(`${bundleId}:${kind}`,item);return item;},
  accept({actor,projectId,acceptanceId,bundleId,exceptions=[]}){write(actor);get(bundles,id("bundleId",bundleId),projectId,"BUNDLE_NOT_FOUND");id("acceptanceId",acceptanceId);const portability=[...rehearsals.values()].some(x=>x.bundleId===bundleId&&x.result==="passed");if(!portability)throw new DeliveryError("PORTABILITY_REQUIRED","A passing portability verification is required.",409);const item=copy({projectId,acceptanceId,bundleId,exceptions:exceptions.map(x=>String(x).slice(0,300)),acceptedAt:now(),acceptedBy:actor.subject,delivery:"accepted-not-deployed"});acceptance.set(acceptanceId,item);return item;},
  view({actor,projectId}){read(actor);return copy({telemetry:[...telemetry.values()].filter(x=>x.projectId===projectId),releases:[...releases.values()].filter(x=>x.projectId===projectId),artifacts:[...artifacts.values()].filter(x=>x.projectId===projectId),bundles:[...bundles.values()].filter(x=>x.projectId===projectId),rehearsals:[...rehearsals.values()].filter(x=>x.projectId===projectId),acceptance:[...acceptance.values()].filter(x=>x.projectId===projectId)});}
 });
}
