import { createHash, randomUUID } from "node:crypto";
import { HERO_ENVIRONMENTS, NODE_STATES, SECRET_STATES } from "../../contracts/src/infrastructure-control.mjs";
const ID=/^[A-Za-z][A-Za-z0-9._:-]{2,127}$/; const SECRET=/(secret|password|credential|token|authorization|private.?key)/i;
const copy=value=>Object.freeze(structuredClone(value)); const safeId=(label,value)=>{if(typeof value!=="string"||!ID.test(value))throw new InfrastructureError("INVALID_IDENTIFIER",`${label} is invalid.`,400);return value;}; const write=actor=>{if(!actor||!["project-owner","admin"].includes(actor.role))throw new InfrastructureError("PROJECT_WRITE_REQUIRED","Project owner or admin access is required.",403);}; const read=actor=>{if(!actor||!["project-owner","admin","viewer"].includes(actor.role))throw new InfrastructureError("PROJECT_READ_REQUIRED","Project access is required.",403);}; const safe=value=>{if(!value||typeof value!=="object")return value; return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,SECRET.test(k)?"[redacted]":safe(v)]));};
export class InfrastructureError extends Error { constructor(code,message,statusCode=409){super(message);this.name="InfrastructureError";this.code=code;this.statusCode=statusCode;} }
export function createInfrastructureControl({now=()=>new Date().toISOString()}={}) { const servers=new Map(), nodes=new Map(), enrollments=new Map(), desired=new Map(), observed=new Map(), secrets=new Map(), egress=new Map(), repositories=new Map(); const inProject=(record,projectId,code)=>{if(!record||record.projectId!==projectId)throw new InfrastructureError(code,"Resource was not found in this project.",404);return record;};
 return Object.freeze({
  environments(){return HERO_ENVIRONMENTS;},
  registerRepository({actor,projectId,repositoryId,name,defaultBranch="main",metadata={}}){write(actor);safeId("projectId",projectId);safeId("repositoryId",repositoryId); if(repositories.has(repositoryId))throw new InfrastructureError("REPOSITORY_EXISTS","Repository already exists."); const item=copy({projectId,repositoryId,name:String(name).slice(0,160),defaultBranch:String(defaultBranch).slice(0,120),metadata:safe(metadata),mode:"metadata-only-no-github-fetch",createdAt:now(),createdBy:actor.subject});repositories.set(repositoryId,item);return item;},
  onboardServer({actor,projectId,serverId,address,credentialReference,environment="development"}){write(actor);safeId("projectId",projectId);safeId("serverId",serverId); if(!HERO_ENVIRONMENTS.includes(environment)||typeof address!=="string"||address.length<3||typeof credentialReference!=="string"||!/^secret-ref:[A-Za-z][A-Za-z0-9._:-]{2,127}$/.test(credentialReference))throw new InfrastructureError("SERVER_INVALID","Server must use a fixed environment and a secret reference.",400); const item=copy({projectId,serverId,address:address.slice(0,253),credentialReference,environment,state:"planned-no-connection",createdAt:now(),createdBy:actor.subject});servers.set(serverId,item);return item;},
  connectivityPlan({actor,projectId,serverId,bootstrapDigest}){write(actor);const server=inProject(servers.get(safeId("serverId",serverId)),projectId,"SERVER_NOT_FOUND");if(!/^[a-f0-9]{64}$/i.test(bootstrapDigest))throw new InfrastructureError("BOOTSTRAP_DIGEST_INVALID","Bootstrap digest must be SHA-256.",400);return copy({projectId,serverId:server.serverId,prerequisites:["outbound-https","time-sync","isolated-runner","agent-identity"],bootstrapDigest:bootstrapDigest.toLowerCase(),state:"plan-only-no-bootstrap-executed",createdAt:now()});},
  createEnrollment({actor,projectId,nodeId,serverId,expiresAt}){write(actor);safeId("nodeId",nodeId);inProject(servers.get(safeId("serverId",serverId)),projectId,"SERVER_NOT_FOUND");if(nodes.has(nodeId)||enrollments.has(nodeId))throw new InfrastructureError("NODE_EXISTS","Node already exists."); const nonce=randomUUID();const item=copy({projectId,nodeId,serverId,nonceHash:createHash("sha256").update(nonce).digest("hex"),expiresAt,state:"pending",issuedAt:now(),issuedBy:actor.subject});enrollments.set(nodeId,item);return copy({...item,enrollmentNonce:nonce});},
  registerNode({projectId,nodeId,enrollmentNonce,identityFingerprint,capabilities=[]}){safeId("projectId",projectId);const enrollment=inProject(enrollments.get(safeId("nodeId",nodeId)),projectId,"ENROLLMENT_NOT_FOUND");if(enrollment.state!=="pending"||Date.parse(enrollment.expiresAt)<Date.parse(now())||createHash("sha256").update(String(enrollmentNonce)).digest("hex")!==enrollment.nonceHash)throw new InfrastructureError("ENROLLMENT_REJECTED","Enrollment is expired, used or invalid.",403); if(typeof identityFingerprint!=="string"||identityFingerprint.length<16)throw new InfrastructureError("NODE_IDENTITY_INVALID","Node identity is invalid.",400); const item=copy({projectId,nodeId,serverId:enrollment.serverId,identityFingerprint,capabilities:capabilities.map(String).slice(0,50),state:"registered",registeredAt:now(),lastHeartbeatAt:null,rotationVersion:1});nodes.set(nodeId,item);enrollments.set(nodeId,copy({...enrollment,state:"consumed",consumedAt:now()}));return item;},
  heartbeat({projectId,nodeId,identityFingerprint,capabilities=[]}){const node=inProject(nodes.get(safeId("nodeId",nodeId)),projectId,"NODE_NOT_FOUND");if(node.state!=="registered"||node.identityFingerprint!==identityFingerprint)throw new InfrastructureError("NODE_IMPERSONATION_REJECTED","Node identity is not valid.",403);const next=copy({...node,capabilities:capabilities.map(String).slice(0,50),lastHeartbeatAt:now()});nodes.set(nodeId,next);return next;},
  rotateNodeIdentity({actor,projectId,nodeId,identityFingerprint}){write(actor);const node=inProject(nodes.get(safeId("nodeId",nodeId)),projectId,"NODE_NOT_FOUND");if(typeof identityFingerprint!=="string"||identityFingerprint.length<16)throw new InfrastructureError("NODE_IDENTITY_INVALID","Node identity is invalid.",400);const next=copy({...node,identityFingerprint,rotationVersion:node.rotationVersion+1,rotatedAt:now(),rotatedBy:actor.subject});nodes.set(nodeId,next);return next;},
  revokeNode({actor,projectId,nodeId,reason}){write(actor);const node=inProject(nodes.get(safeId("nodeId",nodeId)),projectId,"NODE_NOT_FOUND");const next=copy({...node,state:"revoked",revokedAt:now(),revokedBy:actor.subject,reason:String(reason).slice(0,500)});nodes.set(nodeId,next);return next;},
  setState({actor,projectId,environment,desiredState,observedState}){write(actor);if(!HERO_ENVIRONMENTS.includes(environment))throw new InfrastructureError("ENVIRONMENT_INVALID","Only Development, Test and Production exist in v1.",400);const key=`${projectId}:${environment}`;const version=(desired.get(key)?.version??0)+1;const target=copy({projectId,environment,state:safe(desiredState),version,updatedAt:now(),updatedBy:actor.subject});desired.set(key,target);observed.set(key,copy({projectId,environment,state:safe(observedState),observedAt:now()}));return target;},
  reconcile({actor,projectId,environment}){read(actor);const key=`${projectId}:${environment}`,target=desired.get(key),actual=observed.get(key);if(!target||!actual)throw new InfrastructureError("STATE_NOT_FOUND","Desired and observed state are required.",404);const differences=Object.keys({...target.state,...actual.state}).filter(k=>JSON.stringify(target.state[k])!==JSON.stringify(actual.state[k])).sort();return copy({projectId,environment,differences,decision:differences.length?"proposal-required":"in-sync",automaticExecution:"forbidden-without-separate-dispatch",desiredVersion:target.version});},
  registerSecret({actor,projectId,secretId,reference,operation="registered"}){write(actor);safeId("secretId",secretId);if(!SECRET_STATES.includes(operation)||typeof reference!=="string"||!/^secret-ref:[A-Za-z][A-Za-z0-9._:-]{2,127}$/.test(reference))throw new InfrastructureError("SECRET_METADATA_INVALID","Only a non-sensitive secret reference may be stored.",400);const prior=secrets.get(secretId);if(prior&&prior.projectId!==projectId)throw new InfrastructureError("SECRET_CROSS_PROJECT","Secret belongs to another project.",409);const item=copy({projectId,secretId,reference,state:operation,version:(prior?.version??0)+1,updatedAt:now(),updatedBy:actor.subject,value:"never-stored-or-revealed"});secrets.set(secretId,item);return item;},
  requestReveal({actor,projectId,secretId,mfaFresh,reAuthenticated,reason}){if(!actor||actor.role!=="project-owner")throw new InfrastructureError("OWNER_REQUIRED","Only the owner may request a reveal.",403);const secret=inProject(secrets.get(safeId("secretId",secretId)),projectId,"SECRET_NOT_FOUND");if(!mfaFresh||!reAuthenticated||typeof reason!=="string"||reason.trim().length<8)throw new InfrastructureError("REVEAL_GUARD_FAILED","Fresh MFA, re-authentication and reason are required.",403);return copy({projectId,secretId,reference:secret.reference,state:"reveal-request-recorded",value:"not-returned-by-control-plane",expiresAt:new Date(Date.parse(now())+5*60_000).toISOString(),reason:reason.slice(0,500),audit:true});},
  setEgressPolicy({actor,projectId,tools=[],domains=[]}){write(actor);const item=copy({projectId,tools:[...new Set(tools.map(String))].sort(),domains:[...new Set(domains.map(String).map(x=>x.toLowerCase()))].sort(),default:"deny",updatedAt:now(),updatedBy:actor.subject});egress.set(projectId,item);return item;},
  view({actor,projectId}){read(actor);return copy({environments:HERO_ENVIRONMENTS,servers:[...servers.values()].filter(x=>x.projectId===projectId),nodes:[...nodes.values()].filter(x=>x.projectId===projectId),secrets:[...secrets.values()].filter(x=>x.projectId===projectId),egress:egress.get(projectId)??null,repositories:[...repositories.values()].filter(x=>x.projectId===projectId)});}
 });
}
