import { SYSTEM_ENTITY_LIFECYCLES, SYSTEM_ENTITY_TYPES } from "../../contracts/src/system-catalog.mjs";
const ID = /^[A-Za-z][A-Za-z0-9._:-]{2,127}$/;
function copy(value) { return Object.freeze(structuredClone(value)); }
function id(label, value) { if (typeof value !== "string" || !ID.test(value)) throw new SystemCatalogError("INVALID_IDENTIFIER", `${label} is invalid.`, 400); return value; }
function editor(actor) { if (!actor || !["project-owner", "admin"].includes(actor.role)) throw new SystemCatalogError("PROJECT_WRITE_REQUIRED", "Project owner or admin access is required.", 403); return actor; }
export class SystemCatalogError extends Error { constructor(code, message, statusCode = 409) { super(message); this.name = "SystemCatalogError"; this.code = code; this.statusCode = statusCode; } }
export function createSystemCatalog({ now = () => new Date().toISOString() } = {}) {
  const entities = new Map(); const dependencies = new Map(); const inventoryPlans = new Map(); const driftProposals = new Map(); const knowledge = new Map();
  function get(entityId, projectId) { const entity = entities.get(id("entityId", entityId)); if (!entity || entity.projectId !== projectId) throw new SystemCatalogError("ENTITY_NOT_FOUND", "Entity was not found in this project.", 404); return entity; }
  return Object.freeze({
    register({ actor, projectId, entityId, type, name, lifecycle = "planned", metadata = {} }) { editor(actor); id("projectId", projectId); id("entityId", entityId); if (!SYSTEM_ENTITY_TYPES.includes(type) || !SYSTEM_ENTITY_LIFECYCLES.includes(lifecycle) || typeof name !== "string" || name.trim().length < 1) throw new SystemCatalogError("ENTITY_INVALID", "Entity type, lifecycle or name is invalid.", 400); const prior = entities.get(entityId); if (prior && prior.projectId !== projectId) throw new SystemCatalogError("ENTITY_CROSS_PROJECT_CONFLICT", "Entity id cannot cross project boundaries.", 409); const entity = copy({ entityId, projectId, type, name: name.trim().slice(0, 160), lifecycle, metadata: structuredClone(metadata), version: (prior?.version ?? 0) + 1, updatedAt: now(), updatedBy: actor.subject }); entities.set(entityId, entity); return entity; },
    link({ actor, projectId, fromEntityId, toEntityId, relation = "depends-on" }) { editor(actor); const from = get(fromEntityId, projectId); const to = get(toEntityId, projectId); if (from.entityId === to.entityId) throw new SystemCatalogError("DEPENDENCY_SELF_REFERENCE", "Entity cannot depend on itself.", 400); const key = `${projectId}:${from.entityId}:${to.entityId}:${relation}`; const link = copy({ dependencyId: key, projectId, fromEntityId: from.entityId, toEntityId: to.entityId, relation: String(relation).slice(0, 80), createdAt: now(), createdBy: actor.subject }); dependencies.set(key, link); return link; },
    list({ projectId, type = null }) { id("projectId", projectId); return Object.freeze([...entities.values()].filter(item => item.projectId === projectId && (!type || item.type === type)).sort((a,b) => a.entityId.localeCompare(b.entityId)).map(copy)); },
    dependencies({ projectId, entityId }) { get(entityId, projectId); return Object.freeze([...dependencies.values()].filter(item => item.projectId === projectId && (item.fromEntityId === entityId || item.toEntityId === entityId)).map(copy)); }
    ,recordRepositoryInventory({ actor, projectId, repositoryEntityId, observed = {} }) {
      editor(actor); const repository = get(repositoryEntityId, projectId); if (repository.type !== "repository") throw new SystemCatalogError("REPOSITORY_REQUIRED", "Inventory can only bind to a repository entity.", 400);
      const plan = copy({ inventoryId: `inventory-${repositoryEntityId}-${repository.version}`, projectId, repositoryEntityId, mode: "local-observed-metadata", observed: structuredClone(observed), state: "recorded-no-external-fetch", recordedAt: now(), recordedBy: actor.subject }); inventoryPlans.set(plan.inventoryId, plan); return plan;
    },
    detectDrift({ actor, projectId, entityId, observed = {} }) {
      editor(actor); const entity = get(entityId, projectId); const desired = entity.metadata?.desired ?? {}; const differences = Object.keys({ ...desired, ...observed }).filter(key => JSON.stringify(desired[key]) !== JSON.stringify(observed[key])).sort();
      const proposal = copy({ driftProposalId: `drift-${entityId}-${entity.version}-${driftProposals.size + 1}`, projectId, entityId, state: differences.length ? "proposed" : "no-drift", differences, desired: structuredClone(desired), observed: structuredClone(observed), overwrite: "forbidden", createdAt: now(), createdBy: actor.subject }); driftProposals.set(proposal.driftProposalId, proposal); return proposal;
    },
    attachReferences({ actor, projectId, entityId, references }) { editor(actor); const entity = get(entityId, projectId); const allowed = ["owner", "team", "document", "run", "artifact", "health"]; const normalized = {}; for (const [key, value] of Object.entries(references ?? {})) { if (!allowed.includes(key)) throw new SystemCatalogError("REFERENCE_INVALID", `Unsupported reference ${key}.`, 400); normalized[key] = String(value); } const next = copy({ ...entity, metadata: { ...entity.metadata, references: normalized }, version: entity.version + 1, updatedAt: now(), updatedBy: actor.subject }); entities.set(entityId, next); return next; },
    registerKnowledge({ actor, projectId, knowledgeId, kind, title, sourceRef, tags = [] }) { editor(actor); id("projectId", projectId); id("knowledgeId", knowledgeId); if (typeof sourceRef !== "string" || !sourceRef.startsWith("hero://")) throw new SystemCatalogError("KNOWLEDGE_SOURCE_INVALID", "Knowledge source must be internal hero:// reference.", 400); const item = copy({ knowledgeId, projectId, kind: String(kind).slice(0, 80), title: String(title).slice(0, 240), sourceRef, tags: tags.map(String), createdAt: now(), createdBy: actor.subject }); knowledge.set(knowledgeId, item); return item; },
    search({ projectId, query }) { id("projectId", projectId); const needle = String(query ?? "").trim().toLowerCase(); if (needle.length < 2) throw new SystemCatalogError("SEARCH_QUERY_INVALID", "Search query is too short.", 400); return Object.freeze([...entities.values(), ...knowledge.values()].filter(item => item.projectId === projectId && JSON.stringify(item).toLowerCase().includes(needle)).map(item => copy(item))); },
    blastRadius({ projectId, entityId }) { get(entityId, projectId); const reached = new Set([entityId]); let changed = true; while (changed) { changed = false; for (const link of dependencies.values()) if (link.projectId === projectId && reached.has(link.toEntityId) && !reached.has(link.fromEntityId)) { reached.add(link.fromEntityId); changed = true; } } return Object.freeze([...reached].sort()); }
  });
}
