export const HERO_SERVICE = "hero-control-plane";
export const HERO_VERSION = "0.1.0";
export const HERO_BOUNDARY = "clean-room";

export {
  ARCHITECTURE_CONTRACT_VERSION,
  ARCHITECTURE_FLOW,
  ARCHITECTURE_GUARDRAILS,
  ARCHITECTURE_LAYERS,
  ARCHITECTURE_RUNTIME,
  ARCHITECTURE_STYLE,
  PROVIDER_ARCHITECTURE,
  getPublicArchitectureSummary,
  validateArchitectureContract
} from "./architecture.mjs";

export {
  ALWAYS_SEPARATELY_APPROVED_ACTIONS,
  COLLABORATION_MODES,
  SIMPLE_DEVELOPMENT_STATUSES,
  USER_EXPERIENCE_CONTRACT_VERSION,
  USER_EXPERIENCE_LANGUAGE,
  UX_QUESTION_POLICY,
  UX_REQUIRED_SCREENS,
  validateUserExperienceContract
} from "./user-experience.mjs";
