export const INFRASTRUCTURE_CONTROL_CONTRACT_VERSION = "1.2";
/** BO-121: exactly three environments in v1; a custom environment is rejected, not created. */
export const HERO_ENVIRONMENTS = Object.freeze(["development", "test", "production"]);
export const NODE_STATES = Object.freeze(["pending", "registered", "offline", "revoked"]);
export const SECRET_STATES = Object.freeze(["registered", "replaced", "rotated", "revoked"]);

/** BO-123: the Hero Node Agent protocol. The node always dials out; Hero never opens a connection to it. */
export const NODE_PROTOCOL_VERSION = "1.0";
export const NODE_HEARTBEAT_INTERVAL_SECONDS = 30;
export const NODE_OFFLINE_AFTER_SECONDS = 120;
export const NODE_CAPABILITIES = Object.freeze(["runner", "reconciler", "telemetry", "builder"]);
/** Persist every Nth heartbeat (and every state change); the sequence floor survives a restart within this window. */
export const NODE_HEARTBEAT_PERSIST_EVERY = 10;

/** BO-129: environment-specific runners with a hard concurrency ceiling. */
export const RUNNER_MAX_CONCURRENCY = 8;
export const RUNNER_ISOLATION = "container-per-run";

/** BO-131: a reveal is requested, never returned by the Control Plane, and expires quickly. */
export const REVEAL_MAX_SECONDS = 300;

/** BO-122: the read-only GitHub metadata the adapter may describe. No file contents, no tokens. */
export const GITHUB_METADATA_KINDS = Object.freeze(["repository", "branch", "workflow", "release", "deployment"]);
export const GITHUB_ALLOWED_PATHS = Object.freeze([
  /^\/repos\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/,
  /^\/repos\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/branches$/,
  /^\/repos\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/actions\/workflows$/,
  /^\/repos\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/releases$/,
  /^\/repos\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/deployments$/
]);

/**
 * BO-124: the threat model. Every threat names the control and the test that proves it,
 * and an executable check keeps the list and the tests in step.
 */
export const INFRASTRUCTURE_THREAT_MODEL = Object.freeze([
  Object.freeze({ id: "T1", threat: "Agent impersonation: someone presents another node's identity", control: "per-node token (hash only stored) plus identity fingerprint on every heartbeat", test: "BO-134 impersonation" }),
  Object.freeze({ id: "T2", threat: "Replay of a captured heartbeat or enrollment", control: "strictly increasing sequence per node and a one-time enrollment nonce that expires", test: "BO-134 replay" }),
  Object.freeze({ id: "T3", threat: "Agent compromise: a node is taken over", control: "rotate and revoke; a revoked or rotated token is refused at once", test: "BO-134 rotate-revoke" }),
  Object.freeze({ id: "T4", threat: "Inbound exposure: Hero reaching into a customer server", control: "outbound-only protocol; Hero holds no connection and the plan executes nothing", test: "BO-134 outbound-only" }),
  Object.freeze({ id: "T5", threat: "Poisoned bootstrap artifact", control: "bootstrap artifact is generated by Hero and pinned by SHA-256; a different digest is refused", test: "BO-134 bootstrap-checksum" }),
  Object.freeze({ id: "T6", threat: "Command forgery to a node", control: "commands are signed proposals only; nothing runs without a separate dispatch", test: "BO-134 reconcile-proposal" }),
  Object.freeze({ id: "T7", threat: "Secret leak through records, logs or the page", control: "references only; keys that look like credentials are redacted before storage", test: "BO-134 credential-leak" }),
  Object.freeze({ id: "T8", threat: "Unbounded egress from a runner", control: "default deny; tool and domain allowlist checked per request", test: "BO-134 egress" }),
  Object.freeze({ id: "T9", threat: "Offline or silent node treated as healthy", control: "no heartbeat inside the window shows the node offline and removes its runners", test: "BO-134 offline" }),
  Object.freeze({ id: "T10", threat: "Cross-project or cross-environment runner use", control: "runner policies are per project and per environment with a concurrency ceiling", test: "BO-134 isolation" })
]);

export function getInfrastructureControlContractSummary() {
  return Object.freeze({
    version: INFRASTRUCTURE_CONTROL_CONTRACT_VERSION,
    environments: HERO_ENVIRONMENTS,
    nodeStates: NODE_STATES,
    nodeProtocol: Object.freeze({ version: NODE_PROTOCOL_VERSION, direction: "outbound-only", heartbeatSeconds: NODE_HEARTBEAT_INTERVAL_SECONDS, offlineAfterSeconds: NODE_OFFLINE_AFTER_SECONDS, capabilities: NODE_CAPABILITIES }),
    targetSelection: "Test-only, project-scoped, versioned and record-only until a separate Product Test dispatch is authorized",
    secrets: "metadata-only; values never enter Control Plane records; a reveal is recorded and never returned",
    github: "read-only metadata through an injected adapter; no live call is made by default",
    runners: Object.freeze({ isolation: RUNNER_ISOLATION, maxConcurrency: RUNNER_MAX_CONCURRENCY }),
    egress: "default deny with a tool and domain allowlist",
    threats: INFRASTRUCTURE_THREAT_MODEL.length
  });
}

export function validateInfrastructureControlContract() {
  const errors = [];
  if (HERO_ENVIRONMENTS.join(",") !== "development,test,production") errors.push("Invalid infrastructure-control contract.");
  if (!NODE_STATES.includes("revoked")) errors.push("Invalid infrastructure-control contract.");
  if (new Set(INFRASTRUCTURE_THREAT_MODEL.map(item => item.id)).size !== INFRASTRUCTURE_THREAT_MODEL.length) errors.push("Threat identifiers must be unique.");
  return errors;
}
